name: 💡[Co-Create] Idea Generation
description: File an idea for Co-Creation
title: "[Co-Create - IDEA] IDEA TITLE"
labels: ["co-create","idea"]
body:
- type: textarea
  attributes:
    label: Describe the idea
    description: A concise description of what you'd like. Please provide as much related information as possible including screenshots, documents, links etc.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Outcome
    description: A concise description of what you expected to happen. Please provide as much related information as possible including screenshots, documents, links etc.
  validations:
    required: false
- type: dropdown
  id: component
  attributes:
    label: What department are you with?
    options:
      - Customer Servise
      - Distribution Operation
      - Human Resources
      - Audit
      - Information Technology
      - Other
  validations:
    required: true
- type: textarea
  attributes:
    label: Why do you feel this is important?
    description: Explain why this is important to you and how many people would benefit from it.
    placeholder: |
      1. Its important because...
      2. It would benefit x number of employees...
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
