name: ❓[Co-Create] Question
description: Ask a question about the Co-Creation project
title: "[Co-Create - QUESTION] QUESTION"
labels: ["co-create", "question"]
body:
- type: textarea
  attributes:
    label: What is your question?
    description: A concise description of what you need to know. Please provide as much related information as possible including screenshots, documents, links etc.
  validations:
    required: true
- type: dropdown
  id: component
  attributes:
    label: Which product is your question about?
    options:
      - Pre Job Brief Canvas App
      - eDVIR Canvas App
      - Agent Assist Custom Conenctor
  validations:
    required: true