name: ❓[Co-Create] Question
description: Ask a question about the Co-Creation
title: "[Co-Create - QUESTION] QUESTION"
labels: ["co-create", "question"]
body:
- type: textarea
  attributes:
    label: What is your question?
    description: A concise description of what you need to know. Please provide as much related information as possible including screenshots, documents, links etc.
  validations:
    required: true
- type: dropdown
  id: component
  attributes:
    label: What component are you experiencing the issue with?
    options:
      - Pre Job Brief Canvas App
      - eDVIR Canvas App
      - Agent Assist Custom Conenctor
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: What solution version are you using?
    placeholder: "February 2022 or 1.0.1.2033"
  validations:
    required: true